### ISSUE TITLE
settings button not responding when clicked

### ISSUE THREAD

**Issue by DoleBludgeoner** [ptkdev/chrome-extension-aspectratio219#16]
Settings button press animation works but settings window not coming up when settings button is pressed.

**Comment by ptkdev** [comment]
Refresh page of netflix, youtube, etc after change settings.

**Comment by DoleBludgeoner** [comment]
Hi,

Still not working.
Not a webpage issue as the setting menu does not come up at all.

Have restarted Chrome, pc multiple times which has not rectified the issue.

Using Chrome 89.0.4389.82 64 bit.

Have recorded the issue and provided it in the link below if this helps

https://drive.google.com/file/d/19B-xmrq_iS2W-uTrfIeqXp0dxwnOo_Bi/view?usp=drivesdk

Thanks,

Richard

**Comment by DoleBludgeoner** [comment]
Sooo just realised I had to scroll down for more options.

Would the scroll bar on the side be made easier to see for future users? Or maybe it was an issue with just me.

Anyway, thanks for your help!

**Comment by ptkdev** [comment]
Bro this is a tab-menu. Settings is default and current/active section.

**Comment by DoleBludgeoner** [comment]
Is a 4k screen and me not wearing my glasses a good defense? 😬

Thanks for your help though :)
