### ISSUE TITLE
[Bug] Top and bottom black bars

### ISSUE THREAD

**Issue by DoleBludgeoner** [ptkdev/chrome-extension-aspectratio219#17]
### Feature description

Disney+ support

### Feature motivation

Watch Disney+ with no boarders (currently image is centred within ultrawide monitor due to existing top and bottom bars in actual streamed content footage

**Comment by ptkdev** [comment]
Hi!
Try edit Scale Y and Scale X. Not work?

**Comment by DoleBludgeoner** [comment]
Only just figured out I have to scroll down for more settings.

Will adjust the values and let you know!

Thanks,

Richard
