### ISSUE TITLE
Nothing?

### ISSUE THREAD

**Issue by ChazzLayne** [ptkdev/chrome-extension-aspectratio219#2]
This does not appear to do anything at all to Prime Video, despite the fact I've tried toggling it's switch (as well as all-on and all-off).

**Comment by ptkdev** [comment]
@ChazzLayne no issue here. My settings:
- prime video: on
- Active only in fullscreen mode: on
- open primevideo, open film, go to full screen = **work**

**Solutions 1:**
Try adjust "Set ratio value", default is `1.33` | `0` if you use different aspect ratio than 21:9 ulrawide. Refresh the page after edit of settings (in popup)

**Solutions 2:**
- Disable primevideo toggle
- write `primevideo.com` in "experimental" section
- refresh prime video page, and retry
