### ISSUE TITLE
change in aspect requires refresh of page

### ISSUE THREAD

**Issue by RandomDredd** [ptkdev/chrome-extension-aspectratio219#30]
### Question

everytime i change the aspect ratio through the plugin or the shortcut keys i have to refresh the page in order for it to work.. is that a bug or currently how it works? if it is currently how it works can  we do something to fix that?

I would also like it to remember my selection crop/zoom when i select 21:9 ratio

**Comment by ptkdev** [comment]
Yes, if you change settings/toggle you need refresh page. In future i think to add new toggle button like "automatically refresh the page"

**Comment by RandomDredd** [comment]
it will be better if you can make changes on the fly without needing to refresh, I've seen others do that before.
at the very least when you make a change having it automatically refresh the page would better than a setting/toggle

but I want to thank you for your speedy response and for an extension that actually works.. tried all the offerings on the chrome store and yours is the only one that worked.
