### ISSUE TITLE
Can't have a Custom Crop profile

### ISSUE THREAD

**Issue by Matthius453** [ptkdev/chrome-extension-aspectratio219#5]
- **Chrome Version:**  83.0.4103.97 
- **Plugin Version:** Latest
- **Monitor resolution:** 2560x1080
- **Operating System:** Windows 10

### Expected Behavior

To remember the pre-defined User Crop setting

### Actual Behavior

When toggling away from the Force Crop/Zoom Mode, e.g. back to 16:9 you will lose the Custom Crop settings which for me is 16:9, Cropped and Zoomed to 21:9 so 1.33 Width and 1.33 Height. Changing back to 16:9 sets this to 1 Width and 1 Height, as the previous settings aren't remembered, you have to manually set them again

### Steps to Reproduce

1. Set a keybind for 16:9 and force Crop + Zoom Mode
2. In GUI select 21:9 and then Crop + Zoom
3. Press the 16:9 Shortcut and refresh the page, observe the ratio is set to 1:1. Pressing the crop + zoom mode is not remembered. It will just stretch to 21:9 so everything looks out of proportion

**Comment by ptkdev** [comment]
Thank's for reporting! I checked and you're right, i try add fix in next release.

**Comment by ptkdev** [comment]
Available in **v1.5.2**
